### ISSUE TITLE
Conjugate for parameter \mu of the JR model

### ISSUE THREAD

**Issue by SebaGraz** [mmider/BridgeSDEInference.jl#30]
I would like to re-use Marcin code in fitzHughNagumo_conjugateUpdt.jl in order to implement the conjugate posterior for \mu of the JR model (see section 3 of the notes https://www.overleaf.com/2487461149mmywgchrdbgr ). It seems to me that for doing that I need to re-parametrize all the known parameters in order to define \phi^c and have a drift of the form 
b(x) = \mu \phi + \sum_{j =2 ^N} \theta_j \phi_j^c(x).

Is this true or there is a way to use the code when the drift is of the form

b(x) = \mu \phi + R(x) 
R(x) is function of all the other parameters which we consider fixed and known in this conjugate update step?

**Comment by mmider** [comment]
You don't need to  re-parametrise this diffusion. In FHN model we did that because it was then easier to write generic code that could pick out any subset of the parameters from the drift to perform conjugate updates. But if you want to perform conjugate updates on `\mu` only then you can just forget about `\sum_{j =2 ^N} \theta_j \phi_j^c(x)` and simply replace any instance of it with a function `R(x)`.

**Comment by SebaGraz** [comment]
Thanks Marcin. Now I think I understood how your implementation works!
